### ISSUE TITLE
Responsive column layout

### ISSUE THREAD

**Issue by jacobthemyth** [jimmythigpen/Homework#4]
# Responsive columns
## Description

Create a simple responsive column layout
### Learning Objectives

After completing this assignment, you should...
- Understand how to use a grid framework to create a responsive layout
- Write SCSS that conforms to a style guide
### Performance Objectives

After completing this assignment, you be able to effectively use
- SCSS
- Bourbon
- Neat
- scss-lint
### Deliverables
- A repo containing at least:
  - `index.html`
  - `main.scss`
### Requirements

See Additional Resources for images of the layouts.
- It should have a desktop layout for when the browser is greater than 840px
  wide.
- It should have a tablet layout when the browser is between 840px and 500px
- It should have a mobile layout when the browser is less than 500px.
- The elements should become smaller as the browser shrinks (see video gif)
- Use the orange color found in the image resources rather than the blue color
  in the screenshots.
### Reading
- http://sass-guidelin.es/#introduction
- https://github.com/necolas/idiomatic-css
- http://cssguidelin.es/#css-selectors
- http://cssguidelin.es/#specificity
- http://sass-guidelin.es/#syntax--formatting
### Screenshots
- [Desktop](https://github.com/TIY-GVL-FEE-2015-Jan/homework-resources/blob/master/responsive-columns/desktop.png)
- [Table](https://github.com/TIY-GVL-FEE-2015-Jan/homework-resources/blob/master/responsive-columns/tablet.png)
- [Mobile](https://github.com/TIY-GVL-FEE-2015-Jan/homework-resources/blob/master/responsive-columns/mobile.png)
### Icons
- [Icons](https://github.com/TIY-GVL-FEE-2015-Jan/homework-resources/tree/master/responsive-columns/icons)

![](https://raw.githubusercontent.com/TIY-GVL-FEE-2015-Jan/homework-resources/master/responsive-columns/video.gif)

**Comment by jimmythigpen** [comment]
git@github.com:jimmythigpen/Responsive.git
